# Generated by Django 4.2.5 on 2023-09-24 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uav_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uavrental',
            name='created',
        ),
    ]
