# Generated by Django 4.2.5 on 2023-09-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav_management', '0002_remove_uavrental_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uav',
            name='category',
            field=models.CharField(choices=[('Tactical', 'Tactical'), ('MALE', 'Medium Altitude Long Endurance (MALE)'), ('HALE', 'High Altitude Long Endurance (HALE)'), ('Mini UAV', 'Mini UAV')], max_length=50),
        ),
    ]
