# Generated by Django 4.2.5 on 2023-09-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav_management', '0004_alter_uav_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uav',
            name='category',
            field=models.CharField(choices=[('Tactical', 'Tactical'), ('MALE', 'Medium Altitude Long Endurance (MALE)'), ('HALE', 'High Altitude Long Endurance (HALE)'), ('Mini UAV', 'Mini UAV')], default='Tactical', max_length=50),
        ),
    ]
