# Generated by Django 4.2.5 on 2023-09-25 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uav_management', '0006_alter_uav_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uavrental',
            options={'ordering': ['-rental_start_date', '-rental_end_date']},
        ),
    ]
